##### __Author:__ Bram Van de Sande

__Date:__ 1 MAY 2018

__Outline:__ Tutorial on how to run the full SCENIC pipeline using the python implementation (i.e. pyscenic).

For this notebook 3005 single cell transcriptomes taken from the mouse brain (somatosensory cortex and hippocampal regions) are used as an example.

> A. Zeisel, A. B. M͡oz-Manchado, S. Codeluppi, P. Lönnerberg, G. L. Manno, A. Juréus, S. Marques, H. Munguba, L. He, C. Betsholtz, C. Rolny, G. Castelo-Branco, J. Hjerling-Leffler, and S. Linnarsson, “Cell types in the mouse cortex and hippocampus revealed by single-cell RNA-seq,” Science, vol. 347, no. 6226, pp. 1138–1142, Mar. 2015.

In [1]:
import pandas as pd
import numpy as np
import os, glob
import pickle
import pyarrow.feather as feather

from arboreto.utils import load_tf_names
from arboreto.algo import grnboost2

from pyscenic.rnkdb import FeatherRankingDatabase as RankingDatabase
#from ctxcore.rnkdb import FeatherRankingDatabase as RankingDatabase
from pyscenic.utils import modules_from_adjacencies
from pyscenic.prune import prune2df, df2regulons
from pyscenic.aucell import aucell

#import seaborn as sns

In [54]:
DATA_FOLDER = "/home/melanie/Documents/Projects/CLL_GRN_conditions/Data/"
RESOURCES_FOLDER="/home/melanie/Documents/Projects/CRCT/pySCENIC/resources/"
DATABASE_FOLDER = "/home/melanie/Documents/Projects/CRCT/pySCENIC/cisTarget_databases/"
#RESULT_FOLDER = "/home/melanie/Documents/Projects/CLL_GRN_conditions/Results/

DATABASES_GLOB = os.path.join(RESOURCES_FOLDER, "hg19-*7species.mc9nr.feather")
MOTIF_ANNOTATIONS_FNAME = os.path.join(RESOURCES_FOLDER, "motifs-v9-nr.hgnc-m0.001-o0.0.tbl")

MM_TFS_FNAME = os.path.join(RESOURCES_FOLDER, 'allTFs_hg38.txt')
SC_EXP_FNAME = os.path.join(DATA_FOLDER, "TPM_normalised_WO.csv")

ADJACENCIES_FNAME = os.path.join(DATA_FOLDER, "adjacencies_CLL_3cond.tsv")
MODULES_FNAME = os.path.join(DATA_FOLDER, "modules_CLL_WO.p")
MOTIFS_FNAME = os.path.join(DATA_FOLDER, "motifs_CLL_WO.csv")
REGULONS_FNAME = os.path.join(DATA_FOLDER, "regulons_CLL_WO.p")
AUCell_FNAME = os.path.join(DATA_FOLDER, "AUcell_CLL_WO.csv")

N_SAMPLES = 500

# Preliminary work

### Load the expression matrix

The scRNA-Seq data is downloaded from GEO: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60361 .

In [55]:
ex_matrix = pd.read_csv(SC_EXP_FNAME, sep=',', header=0, index_col=0).T

Remove duplicate genes.

In [56]:
ex_matrix.head()

,MT-ND1,MT-ND2,MT-CO1,MT-CO2,MT-ATP8,MT-ATP6,MT-CO3,MT-ND3,MT-ND4L,MT-ND4,...,ATP8B2,S100A13,TADA1,SNAP47,TSPAN1,AHCYL1,JMJD4,TNFRSF14,DAP3,YY1AP1
ABC_J1_WO_S34.genes.results.TPM,10.786023,11.228523,12.447537,12.337822,12.751310,12.138428,12.528139,12.160930,11.739387,11.717433,...,4.237737,4.931618,4.466051,5.786355,2.334981,5.071817,4.718979,6.921872,6.598433,5.889289
ABC_J11_WO_S43.genes.results.TPM,10.413441,11.114958,12.426753,12.228306,12.481302,11.894621,12.430980,11.734677,11.478407,11.508584,...,4.201643,5.989565,4.372135,5.562121,2.334981,5.044968,4.372135,6.694064,6.483852,6.130061
ABC_J8_WO_S40.genes.results.TPM,10.693490,10.969280,12.566610,12.201668,11.963921,11.862603,12.357433,11.404577,11.191131,11.640088,...,4.291293,6.241985,4.382547,5.688026,2.334981,5.057543,4.762055,7.085080,6.691389,6.171415
DIC_J1_WO_S10.genes.results.TPM,11.310897,11.625897,12.974404,11.807205,12.397620,11.959224,12.843655,11.938337,12.018170,12.091954,...,4.390166,3.314856,4.329899,5.917803,2.334981,5.295326,4.447733,6.245218,5.993256,5.858466
DIC_J11_WO_S19.genes.results.TPM,12.491495,12.558110,13.121756,12.464393,12.718003,12.269875,12.442402,12.236425,12.156489,12.199229,...,4.295081,3.841548,4.295081,4.766459,2.334981,5.213330,4.386464,7.259417,6.050953,5.941434

In [57]:
ex_matrix.shape

(15, 16188)

### Derive list of Transcription Factors(TF) for _Mus musculus_

List of known TFs for Mm was prepared (cf. notebook).

In [10]:
tf_names = load_tf_names(MM_TFS_FNAME)

In [11]:
len(tf_names)

1892

In [12]:
overlap = set(tf_names) & set(ex_matrix.columns)
len(overlap)

1613

### Load ranking databases

In [13]:
db_fnames = glob.glob(DATABASES_GLOB)
def name(fname):
    return os.path.splitext(os.path.basename(fname))[0]
dbs = [RankingDatabase(fname=fname, name=name(fname)) for fname in db_fnames]

In [14]:
dbs

[FeatherRankingDatabase(name="hg19-tss-centered-5kb-7species.mc9nr"),
 FeatherRankingDatabase(name="hg19-500bp-upstream-7species.mc9nr")]

In [15]:
df = feather.read_table(
    "/home/melanie/Documents/Projects/CRCT/pySCENIC/resources/New_database_files/hg19-500bp-upstream-7species.mc9nr.genes_vs_motifs.rankings.feather"
).to_pandas()

print(df.columns[:10])
print(df.head())

Index(['A1BG', 'A1BG-AS', 'A1CF', 'A2LD1', 'A2M', 'A2ML1', 'A4GALT', 'A4GNT',
       'AA06', 'AAA1'],
      dtype='object')
    A1BG  A1BG-AS   A1CF  A2LD1   A2M  A2ML1  A4GALT  A4GNT   AA06   AAA1  \
0  19697    12964  15692  19436  9944  20837   19169  22064  20913  11448
1  12392    15392  11042   8906  4093  21218   11777  11738   5668   3664
2  19036    10983   3630  18739  8067  20452    7040   2189  20567   9070
3  12094     4900   4571   5666  1099  12104   15227   2627    595  18888
4  15126    19903    614  10992  2256   1526    2633   3169   8387   8936

   ...   ZXDB   ZXDC  ZYG11A  ZYG11B    ZYX  ZZEF1   ZZZ3  psiTPTE22   tAKR  \
0  ...  15077   3072   12674   12673  21064   7338   2574      20395   8755
1  ...   3136   4530    9557   15142   6474  20279   5353       5316  14058
2  ...  13402   3687   10583    1337    306  18888  19421      19903  10844
3  ...   8345  20817   18783   13110  18138  20500  16234       7036  20370
4  ...    151  11461   19162   14458  19930  19216  12152       7320  12665

                                              motifs
0                                   jaspar__MA1023.1
1  taipale_cyt_meth__IRX3_NACGYRNNNNNNYGCGTN_eDBD...
2                      taipale__DBP_DBD_NRTTACGTAAYN
3                                       cisbp__M4240
4                              scertf__macisaac.ACE2

[5 rows x 22285 columns]

# Phase I: Inference of co-expression modules

In the initial phase of the pySCENIC pipeline the single cell expression profiles are used to infer co-expression modules from.

### Run GRNboost from `arboreto` to infer co-expression modules

The arboreto package is used for this phase of the pipeline.

In [15]:
adjancencies = grnboost2(expression_data=ex_matrix, tf_names=tf_names, verbose=True)

preparing dask client
parsing input
creating dask graph
11 partitions
computing dask graph

/home/melanie/miniconda3/envs/pyscenic/lib/python3.10/site-packages/distributed/client.py:3169: UserWarning: Sending large graph of size 11.47 MiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(

shutting down client and local cluster
finished

In [16]:
adjancencies.head()

           TF  target  importance
340     HOXC4  MB21D2  132.133472
1593  LRRFIP1  MOGAT2  121.632641
1168    ASCC1   NLRP2  117.498796
191     FOXO4    NTN4  112.042872
780     HOXB7   LDOC1  109.566635

In [17]:
len(adjancencies)

10305437

In [18]:
adjancencies.to_csv(ADJACENCIES_FNAME, index=False, sep='\t')
# adjancencies = pd.read_csv("/home/melanie/Documents/Projects/DigPhat/Data/ccRCC_data_CEA/epithelial_data/", sep='\t')

In [58]:
adjancencies = pd.read_csv("/home/melanie/Documents/Projects/CLL_GRN_conditions/Results/dynGENIE3/GRN_dynGENIE3_WO.csv")
adjancencies.head()

       TF   target  importance
0   SIRT6     RALA    0.033856
1    JRKL   NSMCE3    0.033751
2  ZNF875  RALGAPB    0.033286
3    MBD1    RPAP1    0.033166
4    NFYA    ERCC5    0.032101

In [59]:
len(adjancencies)

1048575

### Derive potential regulomes from these co-expression modules

Regulons are derived from adjacencies based on three methods.

The first method to create the TF-modules is to select the best targets for each transcription factor:

1. Targets with importance > the 50th percentile.
2. Targets with importance > the 75th percentile
3. Targets with importance > the 90th percentile.

The second method is to select the top targets for a given TF:

1. Top 50 targets (targets with highest weight)

The alternative way to create the TF-modules is to select the best regulators for each gene (this is actually how GENIE3 internally works). Then, these targets can be assigned back to each TF to form the TF-modules. In this way we will create three more gene-sets:

1. Targets for which the TF is within its top 5 regulators
2. Targets for which the TF is within its top 10 regulators
3. Targets for which the TF is within its top 50 regulators

A distinction is made between modules which contain targets that are being activated and genes that are being repressed. Relationship between TF and its target, i.e. activator or repressor, is derived using the original expression profiles. The Pearson product-moment correlation coefficient is used to derive this information.

In addition, the transcription factor is added to the module and modules that have less than 20 genes are removed.

In [60]:
modules = list(modules_from_adjacencies(adjancencies, ex_matrix))

2026-06-24 16:35:24,190 - pyscenic.utils - INFO - Calculating Pearson correlations.

2026-06-24 16:35:24,277 - pyscenic.utils - WARNING - Note on correlation calculation: the default behaviour for calculating the correlations has changed after pySCENIC verion 0.9.16. Previously, the default was to calculate the correlation between a TF and target gene using only cells with non-zero expression values (mask_dropouts=True). The current default is now to use all cells to match the behavior of the R verision of SCENIC. The original settings can be retained by setting 'rho_mask_dropouts=True' in the modules_from_adjacencies function, or '--mask_dropouts' from the CLI.
	Dropout masking is currently set to [False].

2026-06-24 16:35:28,688 - pyscenic.utils - INFO - Creating modules.

In [61]:
with open(MODULES_FNAME, 'wb') as f:
    pickle.dump(modules, f)

with open(MODULES_FNAME, 'rb') as f:
    modules = pickle.load(f)

# Phase II: Prune modules for targets with cis regulatory footprints (aka RcisTarget)

In [62]:
def main():

    df = prune2df(
                dbs,
                modules,
                MOTIF_ANNOTATIONS_FNAME,
                client_or_address="custom_multiprocessing",
                num_workers=4,
                module_chunksize=10,
                weighted_recovery=False,
                rank_threshold=2000,
                auc_threshold=0.01
        )

    df.to_csv(MOTIFS_FNAME)

    regulons = df2regulons(df)
    with open(REGULONS_FNAME, 'wb') as f:
        pickle.dump(regulons, f)

    # AUCell (already memory-friendly if num_workers=1)
    auc_mtx = aucell(
        ex_matrix,
        regulons,
        num_workers=1
    )
    auc_mtx.to_csv(AUCell_FNAME, sep="\t")


if __name__ == "__main__":
    import multiprocessing as mp
    mp.set_start_method("fork", force=True)
    main()

2026-06-24 16:36:27,876 - pyscenic.prune - INFO - Using 4 workers.

2026-06-24 16:36:27,876 - pyscenic.prune - INFO - Using 4 workers.

2026-06-24 16:36:28,621 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(1): database loaded in memory.

2026-06-24 16:36:28,621 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(1): database loaded in memory.

2026-06-24 16:36:28,721 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(2): database loaded in memory.

2026-06-24 16:36:28,721 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(2): database loaded in memory.

2026-06-24 16:36:28,848 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(1): database loaded in memory.

2026-06-24 16:36:28,848 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(1): database loaded in memory.

2026-06-24 16:36:28,938 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(2): database loaded in memory.

2026-06-24 16:36:28,938 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(2): database loaded in memory.

2026-06-24 16:36:29,179 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(2): motif annotations loaded in memory.

2026-06-24 16:36:29,179 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(2): motif annotations loaded in memory.

2026-06-24 16:36:29,199 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(1): motif annotations loaded in memory.

2026-06-24 16:36:29,199 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(1): motif annotations loaded in memory.

2026-06-24 16:36:29,311 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(1): motif annotations loaded in memory.

2026-06-24 16:36:29,311 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(1): motif annotations loaded in memory.

2026-06-24 16:36:29,360 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(2): motif annotations loaded in memory.

2026-06-24 16:36:29,360 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(2): motif annotations loaded in memory.

2026-06-24 16:36:30,780 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ANXA11 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:31,006 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ANXA11 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:33,258 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for BACH1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:37,527 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for BACH1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:38,432 - pyscenic.transform - WARNING - Less than 80% of the genes in BORCS8-MEF2B could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:38,433 - pyscenic.transform - WARNING - Less than 80% of the genes in BORCS8-MEF2B could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:39,333 - pyscenic.transform - WARNING - Less than 80% of the genes in CAT could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:40,159 - pyscenic.transform - WARNING - Less than 80% of the genes in CAT could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:40,402 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CARF could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:40,440 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CAT could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:42,237 - pyscenic.transform - WARNING - Less than 80% of the genes in CHAMP1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:42,716 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHAMP1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:42,741 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHD1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:42,943 - pyscenic.transform - WARNING - Less than 80% of the genes in CHAMP1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:43,747 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CARF could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:43,786 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CAT could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:43,849 - pyscenic.transform - WARNING - Less than 80% of the genes in CREB3L2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:44,043 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREB3L2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:45,321 - pyscenic.transform - WARNING - Less than 80% of the genes in CREB3L2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:45,402 - pyscenic.transform - WARNING - Less than 80% of the genes in CREBZF could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:45,499 - pyscenic.transform - WARNING - Less than 80% of the genes in CREBZF could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:45,880 - pyscenic.transform - WARNING - Less than 80% of the genes in CREM could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:45,995 - pyscenic.transform - WARNING - Less than 80% of the genes in CREM could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:46,019 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHAMP1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:46,044 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHD1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:47,038 - pyscenic.transform - WARNING - Less than 80% of the genes in CYB5R1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:47,851 - pyscenic.transform - WARNING - Less than 80% of the genes in CYB5R1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:48,077 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREB3L2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:49,020 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DIDO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:49,384 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DUSP22 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:52,907 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DIDO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:53,294 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DUSP22 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:53,718 - pyscenic.transform - WARNING - Less than 80% of the genes in ELK1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:54,216 - pyscenic.transform - WARNING - Less than 80% of the genes in ELK3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:55,053 - pyscenic.transform - WARNING - Less than 80% of the genes in ENO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:36:56,045 - pyscenic.transform - WARNING - Less than 80% of the genes in ELK1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:56,551 - pyscenic.transform - WARNING - Less than 80% of the genes in ELK3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:36:56,601 - pyscenic.transform - WARNING - Less than 80% of the genes in ENO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:00,200 - pyscenic.transform - WARNING - Less than 80% of the genes in FIP1L1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:00,725 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ENO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:00,874 - pyscenic.transform - WARNING - Less than 80% of the genes in FIP1L1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:01,432 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ENO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:02,360 - pyscenic.transform - WARNING - Less than 80% of the genes in FOSB could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:02,432 - pyscenic.transform - WARNING - Less than 80% of the genes in FOXK1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:03,029 - pyscenic.transform - WARNING - Less than 80% of the genes in FOSB could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:03,892 - pyscenic.transform - WARNING - Less than 80% of the genes in FOXK1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:07,604 - pyscenic.transform - WARNING - Less than 80% of the genes in GPBP1L1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:07,810 - pyscenic.transform - WARNING - Less than 80% of the genes in GPBP1L1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:09,107 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for FOXO4 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:09,622 - pyscenic.transform - WARNING - Less than 80% of the genes in GTF3C5 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:10,200 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GATAD1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:10,209 - pyscenic.transform - WARNING - Less than 80% of the genes in GTF3C5 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:12,643 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for FOXO4 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:14,588 - pyscenic.transform - WARNING - Less than 80% of the genes in HSF2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:15,219 - pyscenic.transform - WARNING - Less than 80% of the genes in IKZF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:15,443 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GATAD1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:15,525 - pyscenic.transform - WARNING - Less than 80% of the genes in HSF2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:15,674 - pyscenic.transform - WARNING - Less than 80% of the genes in IKZF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:16,152 - pyscenic.transform - WARNING - Less than 80% of the genes in ING3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:16,180 - pyscenic.transform - WARNING - Less than 80% of the genes in ING4 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:16,306 - pyscenic.transform - WARNING - Less than 80% of the genes in ING3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:16,803 - pyscenic.transform - WARNING - Less than 80% of the genes in ING4 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:21,500 - pyscenic.transform - WARNING - Less than 80% of the genes in KDM5A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:22,771 - pyscenic.transform - WARNING - Less than 80% of the genes in KDM5A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:30,768 - pyscenic.transform - WARNING - Less than 80% of the genes in MBTPS2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:31,369 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KDM2A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:31,441 - pyscenic.transform - WARNING - Less than 80% of the genes in MBTPS2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:31,542 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KDM5A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:31,747 - pyscenic.transform - WARNING - Less than 80% of the genes in MEX3C could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:32,431 - pyscenic.transform - WARNING - Less than 80% of the genes in MEX3C could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:32,732 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KMT2A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:32,777 - pyscenic.transform - WARNING - Less than 80% of the genes in MTERF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:32,923 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for LCORL could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:33,315 - pyscenic.transform - WARNING - Less than 80% of the genes in MTF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:33,367 - pyscenic.transform - WARNING - Less than 80% of the genes in MXD3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:33,715 - pyscenic.transform - WARNING - Less than 80% of the genes in MTERF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:33,720 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KDM2A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:33,740 - pyscenic.transform - WARNING - Less than 80% of the genes in MTF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:33,792 - pyscenic.transform - WARNING - Less than 80% of the genes in MXD3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:34,762 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KDM5A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:35,706 - pyscenic.transform - WARNING - Less than 80% of the genes in MYPOP could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:35,733 - pyscenic.transform - WARNING - Less than 80% of the genes in MZF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:36,072 - pyscenic.transform - WARNING - Less than 80% of the genes in NFIL3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:36,605 - pyscenic.transform - WARNING - Less than 80% of the genes in NFKB2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:37,211 - pyscenic.transform - WARNING - Less than 80% of the genes in MYPOP could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:37,236 - pyscenic.transform - WARNING - Less than 80% of the genes in MZF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:39,329 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KMT2A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:39,520 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for LCORL could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:39,666 - pyscenic.transform - WARNING - Less than 80% of the genes in NFIL3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:40,182 - pyscenic.transform - WARNING - Less than 80% of the genes in NFKB2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:44,160 - pyscenic.transform - WARNING - Less than 80% of the genes in PHF2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:45,077 - pyscenic.transform - WARNING - Less than 80% of the genes in PKM could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:45,573 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MZF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:46,428 - pyscenic.transform - WARNING - Less than 80% of the genes in PML could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:46,606 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NFE2L2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:47,613 - pyscenic.transform - WARNING - Less than 80% of the genes in PHF2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:47,737 - pyscenic.transform - WARNING - Less than 80% of the genes in PKM could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:49,130 - pyscenic.transform - WARNING - Less than 80% of the genes in PML could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:50,701 - pyscenic.transform - WARNING - Less than 80% of the genes in PRDM1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:51,794 - pyscenic.transform - WARNING - Less than 80% of the genes in PUM3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:54,429 - pyscenic.transform - WARNING - Less than 80% of the genes in RBPJ could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:54,699 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MZF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:55,227 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NFE2L2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:55,902 - pyscenic.transform - WARNING - Less than 80% of the genes in PRDM1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:56,166 - pyscenic.transform - WARNING - Less than 80% of the genes in PUM3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:37:58,252 - pyscenic.transform - WARNING - Less than 80% of the genes in RNF138 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:58,585 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PIK3C3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:37:59,168 - pyscenic.transform - WARNING - Less than 80% of the genes in RBPJ could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:04,534 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PPP1R10 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:04,655 - pyscenic.transform - WARNING - Less than 80% of the genes in RNF138 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:05,512 - pyscenic.transform - WARNING - Less than 80% of the genes in SNAPC4 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:06,013 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PUM3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:06,660 - pyscenic.transform - WARNING - Less than 80% of the genes in SP2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:09,000 - pyscenic.transform - WARNING - Less than 80% of the genes in SREBF2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:10,962 - pyscenic.transform - WARNING - Less than 80% of the genes in STAT6 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:11,220 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PIK3C3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:11,882 - pyscenic.transform - WARNING - Less than 80% of the genes in STUB1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:12,509 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RFX1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:12,671 - pyscenic.transform - WARNING - Less than 80% of the genes in SNAPC4 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:13,776 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RNF138 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:13,810 - pyscenic.transform - WARNING - Less than 80% of the genes in SP2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:16,071 - pyscenic.transform - WARNING - Less than 80% of the genes in SREBF2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:16,350 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PPP1R10 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:18,661 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PUM3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:19,092 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SMAD5 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:20,049 - pyscenic.transform - WARNING - Less than 80% of the genes in STAT6 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:20,984 - pyscenic.transform - WARNING - Less than 80% of the genes in STUB1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:23,753 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RFX1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:25,887 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RNF138 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:27,766 - pyscenic.transform - WARNING - Less than 80% of the genes in YY1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:28,962 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB25 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:29,067 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB39 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:29,653 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB40 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:29,897 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB6 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:30,484 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TAF1A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:31,735 - pyscenic.transform - WARNING - Less than 80% of the genes in ZCCHC17 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:32,435 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SMAD5 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:34,672 - pyscenic.transform - WARNING - Less than 80% of the genes in ZFP82 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:36,386 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF142 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:37,026 - pyscenic.transform - WARNING - Less than 80% of the genes in YY1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:37,320 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB25 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:37,369 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF155 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:38,196 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB39 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:38,638 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF195 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:38,705 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB40 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:39,022 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF23 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:39,265 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF254 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:39,397 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF264 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:40,195 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB6 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:40,978 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TIMM44 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:42,018 - pyscenic.transform - WARNING - Less than 80% of the genes in ZCCHC17 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:42,098 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TPI1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:42,366 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF304 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:43,176 - pyscenic.transform - WARNING - Less than 80% of the genes in ZFP82 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:43,940 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF324 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:44,324 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF354B could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:44,416 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF367 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:45,809 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF142 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:45,869 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF431 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:45,928 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF433 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:46,348 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF487 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:46,809 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF155 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:47,006 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB10 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:47,225 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF195 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,028 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF524 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,104 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB20 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,116 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF23 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,137 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF527 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,188 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TAF1A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,210 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF543 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,343 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF254 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,484 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF264 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:48,971 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF582 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:49,217 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB37 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:49,571 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF620 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:49,795 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF304 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:50,584 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZCCHC17 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:50,843 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF660 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:50,873 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF324 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:50,892 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZFP3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:51,192 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF688 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:51,246 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF354B could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:52,247 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF367 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:53,595 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF761 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:54,596 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF431 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:54,652 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF433 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:55,073 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF487 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:55,434 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF195 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:55,624 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF211 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:55,686 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF792 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:55,714 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF793 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:55,882 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF224 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:56,310 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF524 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:56,434 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF527 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:56,512 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF543 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:56,840 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF23 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:57,617 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF836 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:57,768 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF846 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:58,081 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF251 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:58,252 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF26 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:58,373 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF266 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:58,836 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TIMM44 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:58,841 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN16 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:58,867 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN18 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:59,690 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:38:59,885 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TPI1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:38:59,969 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN31 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:00,002 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN32 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:00,009 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF582 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:00,149 - pyscenic.transform - WARNING - Less than 80% of the genes in ZZZ3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:00,669 - pyscenic.transform - WARNING - Less than 80% of the genes in ANXA11 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:00,681 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF620 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:00,815 - pyscenic.transform - WARNING - Less than 80% of the genes in ARID3B could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:01,904 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF333 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:01,966 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF660 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:03,161 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF688 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:03,251 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF354B could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:07,341 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF761 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:07,635 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF431 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:08,080 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB10 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:08,317 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB20 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:08,577 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF792 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:08,606 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF793 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:09,443 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB37 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:10,504 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF836 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:10,664 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF846 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:11,649 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZCCHC17 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:11,823 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN16 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:11,850 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN18 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:12,051 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN31 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:12,079 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN32 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:12,289 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF511 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:12,530 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF524 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:12,761 - pyscenic.transform - WARNING - Less than 80% of the genes in CAT could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:12,794 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZFP3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:12,984 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF548 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:13,080 - pyscenic.transform - WARNING - Less than 80% of the genes in ZZZ3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:13,597 - pyscenic.transform - WARNING - Less than 80% of the genes in ANXA11 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:13,876 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF576 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:14,132 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF585A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:14,756 - pyscenic.transform - WARNING - Less than 80% of the genes in ARID3B could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:14,984 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF620 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:15,823 - pyscenic.transform - WARNING - Less than 80% of the genes in CHAMP1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:16,118 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF628 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:16,175 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF630 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:17,512 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF66 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:18,236 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF195 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:18,414 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF211 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:19,531 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF224 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:19,663 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF23 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:20,452 - pyscenic.transform - WARNING - Less than 80% of the genes in DIDO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:20,800 - pyscenic.transform - WARNING - Less than 80% of the genes in DUSP22 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:20,842 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF251 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:20,995 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF26 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:21,586 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF266 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:22,965 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:23,462 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF333 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:23,709 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF793 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:25,518 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF354B could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:25,878 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN16 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:26,647 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for AGAP2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:26,805 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ANXA11 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:27,086 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF431 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:28,719 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ASH2L could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:29,389 - pyscenic.transform - WARNING - Less than 80% of the genes in CAT could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:29,927 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF511 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:30,181 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF524 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:30,611 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF548 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:30,835 - pyscenic.transform - WARNING - Less than 80% of the genes in CHAMP1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:32,114 - pyscenic.transform - WARNING - Less than 80% of the genes in ENO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:32,321 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF576 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:33,392 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF585A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:34,167 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF620 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:35,198 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF628 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:35,250 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF630 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:35,644 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF66 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:36,251 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CAT could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:36,280 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CBFA2T2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:38,142 - pyscenic.transform - WARNING - Less than 80% of the genes in DIDO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:38,522 - pyscenic.transform - WARNING - Less than 80% of the genes in DUSP22 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:39,060 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF793 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:41,010 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHAMP1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:42,632 - pyscenic.transform - WARNING - Less than 80% of the genes in FOXK1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:42,764 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREB3L2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:42,836 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN16 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:43,628 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for AGAP2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:43,709 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREBZF could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:43,772 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ANXA11 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:44,289 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREM could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:45,637 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ASH2L could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:47,368 - pyscenic.transform - WARNING - Less than 80% of the genes in ENO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:47,372 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DIDO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:47,479 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DNMT1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:49,489 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ECSIT could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:52,145 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CAT could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:52,172 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CBFA2T2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:53,552 - pyscenic.transform - WARNING - Less than 80% of the genes in HIVEP2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:53,947 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ENO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:39:54,257 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHAMP1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:55,943 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREB3L2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:56,844 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREBZF could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:57,359 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREM could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:39:58,023 - pyscenic.transform - WARNING - Less than 80% of the genes in ING4 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:00,081 - pyscenic.transform - WARNING - Less than 80% of the genes in FOXK1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:00,421 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DIDO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:00,525 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DNMT1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:01,701 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for FOSB could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:01,782 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for FOXK1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:04,164 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ECSIT could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:05,588 - pyscenic.transform - WARNING - Less than 80% of the genes in KDM2A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:05,765 - pyscenic.transform - WARNING - Less than 80% of the genes in KDM5A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:06,415 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GPBP1L1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:07,569 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GTF3C5 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:07,674 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GZF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:07,701 - pyscenic.transform - WARNING - Less than 80% of the genes in KLF2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:07,821 - pyscenic.transform - WARNING - Less than 80% of the genes in KMT2A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:08,012 - pyscenic.transform - WARNING - Less than 80% of the genes in LCORL could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:08,213 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for HBP1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:08,809 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ENO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:10,082 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for HDAC8 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:10,485 - pyscenic.transform - WARNING - Less than 80% of the genes in HIVEP2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:12,475 - pyscenic.transform - WARNING - Less than 80% of the genes in ING4 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:13,080 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for IKZF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:13,166 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for IKZF4 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:13,247 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ING3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:15,750 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for FOSB could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:17,950 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for FOXK1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:18,293 - pyscenic.transform - WARNING - Less than 80% of the genes in KDM2A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:18,469 - pyscenic.transform - WARNING - Less than 80% of the genes in KDM5A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:20,484 - pyscenic.transform - WARNING - Less than 80% of the genes in KLF2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:20,556 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KDM5A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:20,902 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GPBP1L1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:21,118 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KLF11 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:21,474 - pyscenic.transform - WARNING - Less than 80% of the genes in KMT2A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:21,487 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for LYL1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:21,665 - pyscenic.transform - WARNING - Less than 80% of the genes in LCORL could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:21,983 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GTF3C5 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:22,075 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GZF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:22,145 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for HBP1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:23,302 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MAGOH could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:24,088 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for HDAC8 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:24,297 - pyscenic.transform - WARNING - Less than 80% of the genes in MZF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:24,697 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MAX could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:24,841 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MBTPS2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:26,069 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MORN1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:27,043 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MTERF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:27,814 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for IKZF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:27,900 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for IKZF4 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:27,981 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ING3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:30,388 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MYPOP could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:30,413 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MZF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:31,195 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NFATC2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:32,528 - pyscenic.transform - WARNING - Less than 80% of the genes in NR2C2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:33,148 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NNT could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:34,820 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KDM5A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:34,904 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KLF11 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:35,073 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NR4A2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:35,202 - pyscenic.transform - WARNING - Less than 80% of the genes in PHF2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:36,510 - pyscenic.transform - WARNING - Less than 80% of the genes in MZF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:37,098 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PCK2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:37,257 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PHF2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:37,756 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for LYL1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:39,715 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MAGOH could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:40,000 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for POLD2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:40,310 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MAX could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:41,333 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MBTPS2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:44,193 - pyscenic.transform - WARNING - Less than 80% of the genes in PUM3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:44,762 - pyscenic.transform - WARNING - Less than 80% of the genes in NR2C2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:44,808 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PUM3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:45,126 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MORN1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:45,323 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MTERF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:46,653 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RBPJ could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:47,818 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MYPOP could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:47,847 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MZF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:48,354 - pyscenic.transform - WARNING - Less than 80% of the genes in PHF2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:49,418 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for REST could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:49,728 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RPL35 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:50,212 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NFATC2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:53,847 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NNT could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:54,640 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SNAI3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:55,508 - pyscenic.transform - WARNING - Less than 80% of the genes in SF3B1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:40:56,940 - pyscenic.transform - WARNING - Less than 80% of the genes in PUM3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:57,399 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NR4A2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:59,389 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PCK2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:59,546 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PHF2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:40:59,936 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SREBF2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:00,615 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for POLD2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:02,582 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for STAT6 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:03,460 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for STK40 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:07,920 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PUM3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:10,170 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RBPJ could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:10,549 - pyscenic.transform - WARNING - Less than 80% of the genes in SF3B1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:12,770 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for REST could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:13,968 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RPL35 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:14,299 - pyscenic.transform - WARNING - Less than 80% of the genes in TCF3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:16,389 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TRIB1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:17,078 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TSC22D4 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:17,169 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for U2AF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:17,923 - pyscenic.transform - WARNING - Less than 80% of the genes in TGIF2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:21,112 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for YWHAZ could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:22,098 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:22,260 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB20 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:22,290 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB22 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:22,345 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB25 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:22,372 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:22,599 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SNAI3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:23,504 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB6 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:25,756 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZFPM1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:26,355 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF142 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:26,836 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SREBF2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:28,082 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF23 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:28,319 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF254 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:28,444 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF263 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:30,097 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB20 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:30,272 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for STAT6 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:30,323 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for STK40 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:30,759 - pyscenic.transform - WARNING - Less than 80% of the genes in TCF3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:31,869 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB25 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:32,041 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB37 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:32,154 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB40 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:32,666 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF32 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:33,752 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF333 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:34,060 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF354B could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:34,497 - pyscenic.transform - WARNING - Less than 80% of the genes in ZCCHC17 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:34,566 - pyscenic.transform - WARNING - Less than 80% of the genes in ZDHHC5 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:36,110 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF136 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:36,982 - pyscenic.transform - WARNING - Less than 80% of the genes in TGIF2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:37,433 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF420 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:38,040 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF431 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:38,093 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF433 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:38,147 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF438 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:38,179 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF211 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:38,330 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF460 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:38,501 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF487 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:38,695 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF511 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:39,277 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF224 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:39,358 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF524 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:39,463 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF527 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:39,490 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF529 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:39,543 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF543 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:40,296 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF23 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:40,625 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF559 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:41,547 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF251 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:41,702 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF26 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:41,810 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF266 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:41,848 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF575 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:42,046 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF585A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:42,535 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF620 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:42,831 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF653 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:42,844 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TRIB1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:43,882 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TSC22D4 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:43,965 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for U2AF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:44,311 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF688 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:45,410 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB20 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:45,529 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB25 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:45,632 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF710 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:45,699 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB37 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:46,371 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB40 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:46,974 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF768 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:47,143 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF776 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:47,355 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF35 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:47,471 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF354B could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:47,717 - pyscenic.transform - WARNING - Less than 80% of the genes in ZCCHC17 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:47,780 - pyscenic.transform - WARNING - Less than 80% of the genes in ZDHHC5 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:47,969 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for YWHAZ could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:48,994 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF792 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:49,013 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:49,022 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF793 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:49,182 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB20 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:49,210 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB22 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:49,266 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB25 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:49,294 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:50,341 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF431 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:51,328 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB6 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:51,787 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN16 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:51,817 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN18 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:51,878 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF136 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:52,047 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF487 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:53,501 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ANXA11 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:53,847 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF211 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:54,106 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF224 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:54,140 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF511 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:54,253 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF23 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:54,385 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF524 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:54,537 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF527 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:54,638 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF251 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:54,642 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF532 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:55,680 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF26 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:55,682 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF576 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:55,912 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF585A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:56,088 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZFPM1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:56,676 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF620 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:56,702 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF621 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:57,412 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF266 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:57,938 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF628 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:59,190 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF66 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:41:59,585 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF142 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:41:59,763 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF688 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:01,602 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF761 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:02,026 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF35 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:02,410 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CARF could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:02,836 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF23 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:03,073 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF354B could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:03,911 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF254 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:04,023 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF263 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:04,257 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF793 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:05,007 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF431 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:05,360 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF836 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:06,369 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHAMP1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:06,425 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHD2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:06,649 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF487 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:06,855 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN16 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:06,949 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF511 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:07,312 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF32 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:07,674 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF524 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:07,821 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF527 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:07,952 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF532 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:08,391 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF333 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:09,500 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF354B could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:09,929 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREB3L2 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:10,835 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREBZF could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:10,989 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF420 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:11,077 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF431 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:11,133 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF433 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:11,187 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF438 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:11,350 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREM could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:11,685 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF576 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,229 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF460 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,396 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF487 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,580 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF511 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,736 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF524 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,802 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DIDO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,835 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF527 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,852 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF585A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,861 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF529 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,912 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF543 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:12,912 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DNMT1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:13,140 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DUSP22 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:14,615 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF620 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:14,642 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF621 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:14,831 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF559 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:15,764 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF628 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:16,176 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF66 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:16,779 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF688 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:16,889 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF575 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:17,086 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF585A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:17,549 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF620 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:17,825 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF653 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:18,300 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF688 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:18,710 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF761 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:19,576 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF710 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:20,004 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF768 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:20,174 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF776 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:20,532 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF793 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:21,095 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF792 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:21,123 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF793 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:21,999 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF836 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:22,940 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ENO1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:24,625 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN16 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:24,652 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN18 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:24,851 - pyscenic.transform - WARNING - Less than 80% of the genes in ZSCAN16 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:26,326 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ANXA11 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:31,488 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for FOXK1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:37,457 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GPBP1L1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:41,603 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for HDAC8 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:42,329 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CARF could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:43,749 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for HMGB1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:44,709 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHAMP1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:45,287 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CHD2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:46,525 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREB3L2 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:46,609 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREBZF could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:47,174 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for CREM could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:51,368 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DIDO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:51,489 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DNMT1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:52,586 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for DUSP22 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:42:56,073 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KDM5A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:42:57,296 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KMT2A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:03,548 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MORN1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:04,279 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ENO1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:08,123 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MYPOP could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:08,150 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MZF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:08,208 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NAP1L1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:13,531 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for FOXK1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:19,951 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for GPBP1L1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:20,817 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PHF12 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:23,019 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PML could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:25,032 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for HDAC8 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:27,388 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for HMGB1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:39,649 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KDM5A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:39,971 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RNF138 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:44,756 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for KMT2A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:46,471 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SMAD5 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:47,728 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SNAPC4 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:49,947 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SP110 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:56,124 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MORN1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:58,598 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for STAT6 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:43:59,794 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MYPOP could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:43:59,821 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for MZF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:00,752 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for NAP1L1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:16,963 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TSC22D4 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:17,047 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for U2AF1 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:17,423 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PHF12 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:18,534 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for UBTF could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:19,406 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for PML could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:24,422 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB10 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:24,610 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB20 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:25,565 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB25 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:25,724 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB37 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:27,013 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZCCHC17 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:30,135 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF142 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:33,569 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF211 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:33,787 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF224 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:34,784 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF23 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:35,646 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for RNF138 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:35,868 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF248 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:35,950 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF251 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:36,005 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF254 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:36,190 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF266 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:39,191 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF3 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:40,254 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF32 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:41,353 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF333 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:42,195 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF354B could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:42,292 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SMAD5 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:44,948 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SNAPC4 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:45,209 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF431 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:45,267 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF433 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:45,322 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF438 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:46,074 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for SP110 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:48,605 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF511 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:48,803 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF524 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:50,716 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF576 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:50,849 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF582 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:50,932 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF585A could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:51,493 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF616 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:51,548 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF620 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:52,628 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF628 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:52,683 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF630 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:52,869 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF653 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:53,804 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF66 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:54,312 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF688 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:56,138 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for STAT6 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:44:57,630 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB37 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:44:58,689 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF776 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:01,283 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF792 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:01,313 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF793 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:04,704 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN16 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:05,032 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN9 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:05,084 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZXDA could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:05,430 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(1): All regulons derived.

2026-06-24 16:45:05,430 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(1): All regulons derived.

2026-06-24 16:45:05,471 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(1): Done.

2026-06-24 16:45:05,471 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(1): Done.

2026-06-24 16:45:09,256 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for TSC22D4 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:09,330 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for U2AF1 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:09,909 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for UBTF could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:12,826 - pyscenic.transform - WARNING - Less than 80% of the genes in ZBTB37 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:13,770 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB10 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:13,956 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB20 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:14,059 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB25 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:14,235 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZBTB37 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:17,046 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZCCHC17 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:18,760 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF440 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:21,468 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF142 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:23,723 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF211 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:23,927 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF224 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:24,496 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF23 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:24,737 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF248 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:24,814 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF251 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:24,865 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF254 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:25,816 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF266 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:27,211 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF630 could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:27,738 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF3 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:27,913 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF32 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:28,119 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF333 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:30,760 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF354B could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:33,570 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF431 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:33,628 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF433 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:33,684 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF438 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:36,780 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF511 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:37,237 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF440 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:37,407 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF524 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:37,546 - pyscenic.transform - WARNING - Less than 80% of the genes in ZXDA could be mapped to hg19-500bp-upstream-7species.mc9nr. Skipping this module.

2026-06-24 16:45:37,926 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(2): All regulons derived.

2026-06-24 16:45:37,926 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(2): All regulons derived.

2026-06-24 16:45:38,000 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(2): Done.

2026-06-24 16:45:38,000 - pyscenic.prune - INFO - Worker hg19-500bp-upstream-7species.mc9nr(2): Done.

2026-06-24 16:45:42,853 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF576 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:42,967 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF582 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:43,036 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF585A could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:44,998 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF616 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:45,047 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF620 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:45,972 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF628 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:46,022 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF630 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:46,182 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF653 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:46,275 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF66 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:46,970 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF630 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:48,186 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF688 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:50,612 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF776 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:50,956 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF792 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:50,983 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZNF793 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:54,826 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN16 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:55,540 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZSCAN9 could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:55,590 - pyscenic.transform - WARNING - Less than 80% of the genes in Regulon for ZXDA could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:45:55,921 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(1): All regulons derived.

2026-06-24 16:45:55,921 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(1): All regulons derived.

2026-06-24 16:45:55,954 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(1): Done.

2026-06-24 16:45:55,954 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(1): Done.

2026-06-24 16:46:00,495 - pyscenic.transform - WARNING - Less than 80% of the genes in ZXDA could be mapped to hg19-tss-centered-5kb-7species.mc9nr. Skipping this module.

2026-06-24 16:46:00,790 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(2): All regulons derived.

2026-06-24 16:46:00,790 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(2): All regulons derived.

2026-06-24 16:46:00,872 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(2): Done.

2026-06-24 16:46:00,872 - pyscenic.prune - INFO - Worker hg19-tss-centered-5kb-7species.mc9nr(2): Done.

Create regulons from a dataframe of enriched features.
Additional columns saved: []

100%|████████████████████████████████████████| 419/419 [00:00<00:00, 830.29it/s]

In [63]:
import pickle
import pandas as pd

with open(REGULONS_FNAME, 'rb') as f:
    regulons = pickle.load(f)

edges = []

for reg in regulons:
    tf = reg.transcription_factor
    for target, weight in reg.gene2weight.items():
        edges.append([tf, target, weight])

df = pd.DataFrame(edges, columns=["source", "target", "weight"])
df.to_csv("/home/melanie/Documents/Projects/CLL_GRN_conditions/Results/GRN_CLL_WO_pruned.csv", index=False)

# Phase III: Cellular regulon enrichment matrix (aka AUCell)

Characterize the different cells in a single-cell transcriptomics experiment by the enrichment of the regulons. Enrichment of a regulon is measures as AUC of the recovery curve of the genes that define this regulon.

In [52]:
auc_mtx = aucell(ex_matrix, regulons, num_workers=1)

100%|████████████████████████████████████████| 432/432 [00:00<00:00, 739.00it/s]

In [19]:
sns.clustermap(auc_mtx, figsize=(12,12))

NameError: name 'sns' is not defined

In [53]:
auc_mtx.to_csv(AUCell_FNAME, index=True, sep='\t')